#=================================================================================

eureka:
  instance:
    hostname: cehn-registry

spring:
  profiles:
    active: ${SPRING_PROFILE:dev}

#=================================================================================


