#=================================================================================

server:
  port: 18761

security:
  basic:
    # 启用身份认证
    enabled: false
  user:
    name: cehn-registry
    password: ${REGISTRY_SERVER_PASSWORD:123456}

#=================================================================================

logging:
  config: classpath:log4j2-prod.xml

#================================= 注册中心单节点配置 start =================================

eureka:
  client:
    # 设置是否将自己作为客户端注册到注册中心（缺省true）
    # 是否检索服务。该应用为服务注册中心，职责为注册和发现服务，无需检索服务，设置为 false
    # 这里为不需要（查看@EnableEurekaServer注解的源码，会发现它间接用到了@EnableDiscoveryClient）
    fetch-registry: false
    # 设置是否从注册中心获取注册信息（缺省true）
    # 因为这是一个单点的EurekaServer，不需要同步其它EurekaServer节点的数据，故设为false
    # 如果是多个节点，那这里可以注释掉，或是设置为true
    # 代表不向注册中心注册自己
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    # 为了保证服务的快速发现和注销，我们加这两个参数
    # Eureka 客户端向服务端发送心跳的时间间隔。（默认30）。间隔时间更新多个注册中心之间的服务清单
    lease-renewal-interval-in-seconds: 10
    # 假设上面的参数保证 Eureka 客户端 10s 发送一次心跳，如果客户端突然挂掉了，那 Eureka 服务端就会等下面数值时间，如果客户端还没发送，则剔除该客户端。（默认90）
    lease-expiration-duration-in-seconds: 60

#================================= 注册中心单节点配置 end =================================


#================================= 注册中心高可用配置 start =================================

#================================= 注册中心高可用配置 end =================================

