server:
  port: 18770

  management:
    port: 18870
    security:
      enabled: false

##timeout config
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

debug: true
logging:
  config: classpath:log4j2-dev.xml

zuul:
  sensitive-headers:
  # 忽略某些路径不走网关
  ignored-patterns: /**/admins/**
  # zuul 配合 eureka 会默认创建 serviceId 同名的路由规则，在这里 * 表示所有的服务都不要需要默认规则，我们自己创建映射关系。
  ignored-services: '*'
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  # 设置为 false 可以让业务服务可以拿到 Spring Security 的特定请求头
  ignore-security-headers: false
  host:
    # zuul 中使用 httpclient 调用其他服务时的超时设置
    connect-timeout-millis: 20000
    socket-timeout-millis: 60000
  routes:
    upms:
      sensitiveHeaders:
      path: /ms-api/resource/**
      serviceId: cehn-resource

eureka:
  instance:
    hostname: ms-gateway
    prefer-ip-address: true
    metadataMap:
#      instanceId=${spring.application.name}: ${spring.application.instance_id}
      management.port: ${management.port}
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULTZONE:http://cehn-registry:18761/eureka/}
    registerWithEureka: true
    fetchRegistry: true


---
#=========== ======== 分布式链路跟踪 zipkin 配置 start ======================

spring:
  sleuth:
    sampler:
      # 采样百分比，默认值是 0.1 也就是 10%，记录每一个调用
      percentage: 1.0
  # 使用 stream 存放在 rabbitmq 消息队列
  rabbitmq:
    host: cehn-rabbitmq
    port: 18103
    username: admin
    password: adg123456
---
#==================== 分布式链路跟踪 zipkin 配置 end ========================


