#=================================================================================
# 容器相关设置


#=================================================================================
# spring 组件相关设置
spring:
  profiles:
    active: ${SPRING_PROFILE:dev}


#=================================================================================
# spring cloud 组件相关设置

#关闭安全校验
management:
  endpoint:
    env:
      enabled: false

#=================================================================================
# 其他辅助框架相关配置
